force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Speciality__c.field-meta.xml
<CustomField>
    <fullName>Speciality__c</fullName>
    <label>Speciality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker_Assignment__c/Speaker_Assignment__c.object-meta.xml
<CustomObject>
    <label>Speaker Assignment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Speaker Assignment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaker Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker_Assignment__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Speaker Assignment</relationshipLabel>
    <relationshipName>Speaker_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker_Assignment__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Speaker Assignment</relationshipLabel>
    <relationshipName>Speaker_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SpeakerController.cls
public with sharing class SpeakerController {

    @AuraEnabled
    public static List<Speaker__c> searchSpeakers(String name, String speciality) {
        
        String query = 'SELECT Id, Name, Email__c, Speciality__c FROM Speaker__c WHERE Id != null';
        
        if (String.isNotBlank(name)) {
            query += ' AND Name LIKE \'%' + String.escapeSingleQuotes(name) + '%\'';
        }
        
        if (String.isNotBlank(speciality)) {
            query += ' AND Speciality__c = \'' + String.escapeSingleQuotes(speciality) + '\'';
        }
        
        return Database.query(query);
    }


  @AuraEnabled(cacheable=true)
public static List<Session__c> getSessionsByDate(String sessionDate) {

    Date selectedDate = Date.valueOf(sessionDate);

    return [
        SELECT Id, Name, Title__c, Session_Date__c, Start_Time__c, End_Time__c
        FROM Session__c
        WHERE Session_Date__c = :selectedDate
        ORDER BY Start_Time__c
    ];
}


    @AuraEnabled
    public static Boolean isSpeakerAvailable(Id speakerId, Id sessionId) {

        Session__c newSession = [
            SELECT Session_Date__c, Start_Time__c, End_Time__c
            FROM Session__c WHERE Id = :sessionId
        ];

        for (Speaker_Assignment__c sa : [
            SELECT Session__r.Session_Date__c,
                   Session__r.Start_Time__c,
                   Session__r.End_Time__c
            FROM Speaker_Assignment__c
            WHERE Speaker__c = :speakerId
        ]) {
            if (sa.Session__r.Session_Date__c == newSession.Session_Date__c) {
                Boolean overlap =
                    newSession.Start_Time__c < sa.Session__r.End_Time__c &&
                    newSession.End_Time__c > sa.Session__r.Start_Time__c;
                if (overlap) return false;
            }
        }
        return true;
    }

    @AuraEnabled
    public static void createAssignment(Id speakerId, Id sessionId) {
        insert new Speaker_Assignment__c(
            Speaker__c = speakerId,
            Session__c = sessionId
        );
    }

}